Repository YashBANSAL392/HacktoberFest2023, pull requests merged in 2023-09, with the labels that each got.

#2 Responsiveness Issue resolved
  projectstyle.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#6 Update Project.html
  Project.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 Update Project.html
  Project.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#9 5 check the lower most section and change the css of that
  Project.html
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted
